---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[test::prepare]
      - recipe[nomad::default]
      - recipe[test::exercise]
  - name: client
    driver:
      network:
        - ["private_network", {ip: "192.168.17.242"}]
    run_list:
      - recipe[nomad::client]
    attributes:
      ipaddress: '192.168.17.242'
      nomad:
        config:
          server_list: [ '192.168.17.243:4647' ]
          bind_addr: '192.168.17.242'
      testkitchen:
        ipaddress: '192.168.17.242'

  - name: server
    driver:
      network:
        - ["private_network", {ip: "192.168.17.243"}]
    run_list:
      - recipe[nomad::server]
    attributes:
      nomad:
        config:
          bind_addr: '192.168.17.243'
      testkitchen:
        ipaddress: '192.168.17.243'

